### ISSUE TITLE
I LOVE what you're doing. Please keep going.

### ISSUE THREAD

**Issue by harrysolovay** [ravenscar/franken-srp#1]
Looks like this could be a beautifully-lightweight client! Eager to use it in fact. Please let me know if there's any way I can help out.

**Comment by DavidWells** [comment]
This lib does look great! The amplify auth client is rather large and we are looking for alternatives like this.

**Comment by ravenscar** [comment]
Hey don't worry! I will be back on this next week, after the xmas holidays.

**Comment by harrysolovay** [comment]
Tremendous! Looking forward to using it.

**Comment by joshweir** [comment]
Yeah me too I love cognito.
