### ISSUE TITLE
Started getting WAF block

### ISSUE THREAD

**Issue by elgerg** [ravenscar/franken-srp#13]
Hi,

I love what you did to make it easy to authenticate with AWS.

Recently I get the following response when trying to refresh my token (it had been working perfectly for ages):

```
{
  "name": "SRPError",
  "message": "Request not allowed due to WAF block.",
  "stack": "SRPError: Request not allowed due to WAF block.\n    at IncomingMessage.<anonymous> (/home/pi/.node-red/node_modules/franken-srp/dist/platform/call-cognito.js:61:28)\n    at IncomingMessage.emit (node:events:526:35)\n    at IncomingMessage.emit (node:domain:489:12)\n    at endReadableNT (node:internal/streams/readable:1359:12)",
  "status": 403,
  "action": "Fetch",
  "detail": {
    "responseData": "{\"__type\":\"ForbiddenException\",\"message\":\"Request not allowed due to WAF block.\"}"
  }
}
```

Any idea what I can do to get around this?

Thanks!

**Comment by elgerg** [comment]
@ravenscar do you have any ideas how to get around this issue?
Is there any user agent specified or can one be set?
Thanks

**Comment by ravenscar** [comment]
@elgerg Hey it's not a scenario I have run into as I we do not use WAF with our product yet. I imagine you need to work with your ops team to checkout the WAF logs to see what the root cause of the issue is then put the approprite rules in place to allow the traffic.

**Comment by elgerg** [comment]
Unfortunately it's not a service I have control over. I'm using franken-srp to connect to British Gas Hive Home.

I was hoping it would just be a case of changing the user agent or something that would allow it to get past the WAF block. But I guess if no one else has this issue I'm stuck..

Thanks anyway.
